# This is a basic workflow to help you get started with Actions

name: generate-api-docs

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_call:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate-docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Application Service
        uses: actions/checkout@v3
        with:
          path: application-service
          repository: redhat-appstudio/application-service

      - name: Checkout SPI
        uses: actions/checkout@v3
        with:
          repository: redhat-appstudio/service-provider-integration-operator
          path: service-provider
      
      - name: Checkout GitOps
        uses: actions/checkout@v3
        with:
          repository: redhat-appstudio/managed-gitops
          path: managed-gitops
      
      - name: Checkout KCP
        uses: actions/checkout@v3
        with:
          repository: kcp-dev/kcp
          path: kcp
      
      - name: Install crd-ref-gen
        uses: jaxxstorm/action-install-gh-release@v1.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo: elastic/crd-ref-docs
          tag: v0.0.8

      - name: Generate application-service API docs
        run: crd-ref-docs --log-level=ERROR --config=scripts/config.yaml --output-path=./ref/application-service.md --renderer markdown --source-path=application-service/api/v1alpha1
